# GENERAL CONFIGURATION

# set vi mode for copy mode
setw -g mode-keys vi

# make delay shorter
set -sg escape-time 0

# make window/pane index start with 1
set -g base-index 1
setw -g pane-base-index 1


# KEY BINDINGS

# vi copy mode
bind P paste-buffer
#bind-key -T vi-copy 'v' begin-selection
#bind-key -T vi-copy 'y' copy-selection
#bind-key -T vi-copy 'r' rectangle-toggle

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Split panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Fast pane switching with Alt+vimkey
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Fast window switching with Shift+Alt+vimkey
bind -n M-H previous-window
bind -n M-L next-window

# STATUS BAR AND COLORS

# Force 256 colors
set -g default-terminal "screen-256color"

# Default colors
set-option -g status-bg colour234
set-option -g status-fg colour214

# Hightlight current window
#setw -g window-status-current-fg colour40
#setw -g window-status-current-bg colour234

# Turn off automatic renaming of windows
set-option -g allow-rename off
