general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

label {
    monitor =
    text = $TIME
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -80
    halign = center
    valign = center

    outline_thickness = 2
    dots_size = 0.2
    fade_on_empty = false
    placeholder_text = Password...
}
